default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  min_messages: warning
  variables:
    statement_timeout: 50000
  url: <%= ENV['DATABASE_URL'] %>
  database: maindb
development:
  <<: *default

test:
  <<: *default
production:
  <<: *default
