# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'
gem 'activesupport'
gem 'pg'
gem 'puma'
gem 'rack'
gem 'rack-contrib'
gem 'redis'
gem 'sidekiq'
gem 'sinatra'
gem 'zeitwerk'
