# frozen_string_literal: true

require './config/setup'
Dir['./lib/tasks/**/*.rb'].each { |f| require f }

unless ENV['RACK_ENV'] == 'production'
  require 'rspec/core/rake_task'
  RSpec::Core::RakeTask.new(:spec)

  require 'rubocop/rake_task'
  RuboCop::RakeTask.new do |t|
    t.patterns = ['{lib,spec}/**/*.rb', '{Rake,Gem}file', 'config.ru']
  end

  task default: %i[spec rubocop]
end
